DSO = map.a
OBJS = mapdso.o mapActor.o \
  expMapActor.o linearMapActor.o segmentMapActor.o hidimMapActor.o \
  planeMapActor.o \
  ga.o gacli.o mc.o mcmap.o mcmap2.o mcpath.o mcspace.o mcsurf.o \
  sammon.o edahiro.o \
  ch.o fg.o hull.o io.o mymain.o pointops.o rand.o
include ../Rules.make
