DSO = analyzer.a
OBJS = dsos.o fiddle.o s_print.o m_atom.o m_class.o m_obj.o m_pd.o m_memory.o d_fftroutine.o m_conf.o d_fft.o d_mayer_fft.o d_math.o d_dac.o d_arithmetic.o d_ugen.o amplAnalyzerAlg.o amplAnalyzerHand.o amplAnalyzerActor.o
include ../Rules.make
